baseurl = "https://smarttechie.github.io/hugo-personal-blog/"
theme = "nixon"
title = "John Smith Blog"
languageCode = "en-us"
copyright = "Copyright (c) 2017, blogname.com; all rights reserved."
MetaDataFormat = "yaml"
publishdir = "docs"

# used by Hugo shortcodes
GoogleAnalytics = "UA-XXXXX-Y"

# note that the theme expects author both here and in the
# parameters section
[author]
    name = "John Smith"

# used by the theme
[indexes]
    tag = "tags"
    topic = "topics"

[params]
	copyright_years = "2017"
	css_file = "/css/nixon.css"
	domain_name = "blogname.com"
	personal_site = "http://blogname.com/"

	[params.author]
		name = "John Smith"
		# The three quotes allow the biography to span
		# multiple lines. Must end with three, too.
		short_bio = "Fusce pulvinar dictum magna, vel rutrum nunc tempor non. Curabitur aliquam justo. Pellentesque fringilla libero eget suscipit malesuada."

	[params.facebook]
		account = "facebook_username"
	[params.linkedin]
		account = "linedin_username"
		source  = ""
	[params.twitter]
		account = "twitter_username"
	
  [params.license]
		url = "http://blogname.com/licence"
		attribution = "Licence"
